// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxbOSVeoQI8qmXmaAp8e1fXHI09AGszfM',
    appId: '1:955122467473:web:91635ba4aba8355186f530',
    messagingSenderId: '955122467473',
    projectId: 'in-sight-app',
    authDomain: 'in-sight-app.firebaseapp.com',
    storageBucket: 'in-sight-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOSv2el-15LqusmNr-IJQytC3GcpgqyCo',
    appId: '1:955122467473:android:faeb26b3281eaeda86f530',
    messagingSenderId: '955122467473',
    projectId: 'in-sight-app',
    storageBucket: 'in-sight-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6GY3-hDUN_Yi6kjlwKUyOn2Q0yg4_n6Y',
    appId: '1:955122467473:ios:4e6846ed4492688c86f530',
    messagingSenderId: '955122467473',
    projectId: 'in-sight-app',
    storageBucket: 'in-sight-app.appspot.com',
    iosBundleId: 'com.example.insight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6GY3-hDUN_Yi6kjlwKUyOn2Q0yg4_n6Y',
    appId: '1:955122467473:ios:2c70387b580f53d486f530',
    messagingSenderId: '955122467473',
    projectId: 'in-sight-app',
    storageBucket: 'in-sight-app.appspot.com',
    iosBundleId: 'com.example.insight.RunnerTests',
  );
}
